version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on: 
      - database

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./database_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=f1rexddd@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - 82:80
