version: "3.8"

services:
  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database_data:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - MAX_GOROUTINES=15
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    depends_on: 
      - database
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=f1rexddd@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - 82:80
